(add-to-list 'auto-mode-alist '("[Cc]apfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("[Gg]emfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("[Rr]akefile" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru\\'" . ruby-mode))
