(eval-when-compile (require 'color-theme))
(defun color-theme-mine ()
  "Color theme by Bryan Shell, created 2008-01-09."
  (interactive)
  (color-theme-install
   '(color-theme-mine
     ((background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "#e6e6e6e6e6e6")
      (border-color . "black")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#8a8a8a8a8a8a")
      (cursor-color . "medium turquoise")
      (foreground-color . "#c0c0c0")
      (mouse-color . "black")
      (top-toolbar-shadow-color . "#ffffffffffff"))
     ((senator-eldoc-use-color . t))
     (default ((t (:foreground "#ffffff"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "darkslateblue" :foreground "white"))))
     (c-nonbreakable-space-face ((t (:bold t :background "Red"))))
     (calendar-today-face ((t (:underline t))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue"))))
     (cperl-hash-face ((t (:bold t :background "lightyellow2" :foreground "Red"))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (custom-button-face ((t (:bold t))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment-face ((t (:background "gray85"))))
     (custom-comment-tag-face ((t (:foreground "blue4"))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:underline t :foreground "blue"))))
     (custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "dark green"))))
     (custom-variable-button-face ((t (:underline t :bold t))))
     (custom-variable-tag-face ((t (:underline t :foreground "blue"))))
     (diary-face ((t (:foreground "red"))))

     ;; diff faces
     (diff-context ((t (nil))))

     (diff-added ((t (:foreground "green"))))
     (diff-indicator-added ((t (:inherit 'diff-added))))

     (diff-changed ((t (:foreground "yellow"))))
     (diff-indicator-changed ((t (:inherit 'diff-changed))))

     (diff-refine-change ((t (nil))))

     (diff-removed ((t (:foreground "red"))))
     (diff-indicator-removed ((t (:inherit 'diff-removed))))

;     (diff-file-header)
;     (diff-function)
;     (diff-index)
;     (diff-nonexistent)
     (diff-header
      ((((class color) (min-colors 88) (background dark)) (:background "grey80"))
       (((class color) (min-colors 88) (background light)) (:background "grey45"))
       (((class color) (background light)) (:foreground "blue1" :weight bold))
       (((class color) (background dark)) (:foreground "green" :weight bold))
       (t (:weight bold))))
     (diff-hunk-header ((t (:inherit 'diff-header))))

     ;; dired
     (dired-face-boring ((t (:foreground "gray30"))))
     (dired-face-directory ((t (:bold t :foreground "orange"))))
     (dired-face-executable ((t (:foreground "green4"))))
     (dired-face-flagged ((t (:background "LightSlateGray"))))
     (dired-face-header ((t (:background "grey75" :foreground "black"))))
     (dired-face-marked ((t (:background "PaleVioletRed"))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "cyan4"))))
     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
     (excerpt ((t (nil))))
     (fixed ((t (:bold t))))
     (flyspell-duplicate-face ((t (:underline t :bold t :foreground "Gold3"))))
     (flyspell-incorrect-face ((t (:underline t :bold t :foreground "OrangeRed"))))
     (font-lock-builtin-face ((t (:foreground "#ffaa00"))))
     (font-lock-comment-face ((t (:foreground "Red"))))
     (font-lock-constant-face ((t (:foreground "#00ff00"))))
     (font-lock-doc-string-face ((t (:foreground "green4"))))
     (font-lock-function-name-face ((t (:foreground "#4186be"))))
     (font-lock-keyword-face ((t (:foreground "#00ffff"))))
     (font-lock-preprocessor-face ((t (:foreground "blue3"))))
     (font-lock-reference-face ((t (:foreground "red3"))))
     (font-lock-string-face ((t (:foreground "#ffff00"))))
     (font-lock-type-face ((t (:foreground "Coral"))))
     (font-lock-variable-name-face ((t (:bold t :foreground "white"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red"))))
     (gnus-cite-attribution-face ((t (nil))))
     (gnus-cite-face-1 ((t (:foreground "Khaki"))))
     (gnus-cite-face-2 ((t (:foreground "Coral"))))
     (gnus-cite-face-3 ((t (:foreground "#4186be"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "IndianRed"))))
     (gnus-cite-face-list ((t (:foreground "red"))))
     (gnus-emphasis-bold ((t (:bold t))))
     (gnus-emphasis-bold-italic ((t (:bold t))))
     (gnus-emphasis-italic ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:underline t :bold t))))
     (gnus-emphasis-underline-bold-italic ((t (:underline t :bold t))))
     (gnus-emphasis-underline-italic ((t (:underline t))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4"))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen"))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4"))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen"))))
     (gnus-header-content-face ((t (:foreground "#4186be"))))
     (gnus-header-from-face ((t (:foreground "Coral"))))
     (gnus-header-name-face ((t (:foreground "white"))))
     (gnus-header-newsgroups-face ((t (:foreground "#4186be"))))
     (gnus-header-subject-face ((t (:foreground "#4186be"))))
     (gnus-signature-face ((t (:foreground "white"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick"))))
     (gnus-summary-high-unread-face ((t (:bold t))))
     (gnus-summary-low-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-low-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-low-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-low-unread-face ((t (nil))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#ffffff" :foreground "#000000"))))
     (highlight ((t (:background "#c0c0c0" :foreground "black"))))
     (highlight-changes-delete-face ((t (:underline t :foreground "red"))))
     (highlight-changes-face ((t (:foreground "red"))))
     (holiday-face ((t (:background "pink"))))
     (isearch ((t (:background "paleturquoise"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (nil))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (nil))))
     (jde-java-font-lock-link-face ((t (:underline t :foreground "lightblue"))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "lightblue2"))))
     (jde-java-font-lock-package-face ((t (:foreground "lightblue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (message-cited-text-face ((t (:foreground "white"))))
     (message-header-cc-face ((t (:foreground "#4186be"))))
     (message-header-name-face ((t (:foreground "white"))))
     (message-header-newsgroups-face ((t (:bold t :foreground "Coral"))))
     (message-header-other-face ((t (:foreground "steel blue"))))
     (message-header-subject-face ((t (:bold t :foreground "#4186be"))))
     (message-header-to-face ((t (:bold t :foreground "#4186be"))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-separator-face ((t (:foreground "brown"))))
     (modeline ((t (:background "darkslateblue" :foreground "white"))))
     (modeline-buffer-id ((t (:background "darkslateblue" :foreground "white"))))
     (modeline-mousable ((t (:background "darkslateblue" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "darkslateblue" :foreground "white"))))
     (pointer ((t (:background "#ffffff" :foreground "#000000"))))
     (primary-selection ((t (:background "gray65"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "darkslateblue" :foreground "white"))))
     (right-margin ((t (nil))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (:background "gray90"))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (sgml-doctype-face ((t (:foreground "orange"))))
     (sgml-end-tag-face ((t (:foreground "greenyellow"))))
     (sgml-entity-face ((t (:foreground "gold"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20"))))
     (sgml-sgml-face ((t (:foreground "yellow"))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen"))))
     (show-paren-match-face ((t (:background "purple" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "red" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:underline t :foreground "red"))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (nil))))
     (term-blue ((t (:foreground "#4186be"))))
     (term-bluebg ((t (:background "#4186be"))))
     (term-bold ((t (:bold t))))
     (term-cyan ((t (:foreground "#71bebe"))))
     (term-cyanbg ((t (:background "#71bebe"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-green ((t (:foreground "#e5f779"))))
     (term-greenbg ((t (:background "#e5f779"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "#ef9ebe"))))
     (term-magentabg ((t (:background "#ef9ebe"))))
     (term-red ((t (:foreground "#ef8171"))))
     (term-redbg ((t (:background "#ef8171"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (nil))))
     (term-whitebg ((t (:background "#c0c0c0"))))
     (term-yellow ((t (:foreground "#fff796"))))
     (term-yellowbg ((t (:background "#fff796"))))
     (text-cursor ((t (:background "medium turquoise" :foreground "black"))))
     (toolbar ((t (:background "#ffffff" :foreground "#000000"))))
     (underline ((t (:underline t))))
     (vertical-divider ((t (:background "#ffffff" :foreground "#000000"))))
     (widget ((t (:background "#ffffff" :foreground "#000000"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:background "white" :foreground "dark green"))))
     (widget-field-face ((t (:background "gray85" :foreground "black"))))
     (widget-inactive-face ((t (:background "red" :foreground "dim gray"))))
     (widget-single-line-field-face ((t (:background "gray85" :foreground "black"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "darkslateblue" :foreground "white")))))))
(add-to-list 'color-themes '(color-theme-mine  "My Color Theme" "Bryan Shell"))
